[package]
name = "tetris"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
# Internal dependencies
engine.workspace = true
game.workspace = true
